/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type TeamsAPI interface {

	// AddTeamMembers Post /v1/teams/:teamId/members
	// Add members to team
	AddTeamMembers(c *gin.Context)

	// CreateTeam Post /v1/teams
	// Create team
	CreateTeam(c *gin.Context)

	// DeleteTeam Delete /v1/teams/:teamId
	// Delete team
	DeleteTeam(c *gin.Context)

	// GetTeam Get /v1/teams/:teamId
	// Get team
	GetTeam(c *gin.Context)

	// ListTeamMembers Get /v1/teams/:teamId/members
	// List team members
	ListTeamMembers(c *gin.Context)

	// ListTeams Get /v1/teams
	// List teams
	ListTeams(c *gin.Context)

	// RemoveTeamMembers Delete /v1/teams/:teamId/members
	// Remove members from team
	RemoveTeamMembers(c *gin.Context)

	// UpdateTeam Put /v1/teams/:teamId
	// Update team
	UpdateTeam(c *gin.Context)
}
