/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type SharingAPI interface {

	// CreateShare Post /v1/shares
	// Share file or folder with users/teams
	CreateShare(c *gin.Context)

	// GeneratePublicLink Post /v1/shares/public-links
	// Generate public share link
	GeneratePublicLink(c *gin.Context)

	// GetAcl Get /v1/shares/:resourceType/:resourceId
	// Get ACL for a resource
	GetAcl(c *gin.Context)

	// RevokeAccess Delete /v1/shares/:resourceType/:resourceId/entries/:principalId
	// Revoke access for a principal
	RevokeAccess(c *gin.Context)

	// RevokeAllShares Delete /v1/shares/:resourceType/:resourceId
	// Revoke all sharing for a resource
	RevokeAllShares(c *gin.Context)

	// RevokePublicLink Delete /v1/shares/public-links/:token
	// Revoke public link
	RevokePublicLink(c *gin.Context)

	// UpdatePermission Put /v1/shares/:resourceType/:resourceId/entries/:principalId
	// Update permission for a principal
	UpdatePermission(c *gin.Context)
}
