/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type AdminAPI interface {

	// GetAllowedFileTypes Get /v1/admin/allowed-file-types
	// Get allowed file types
	GetAllowedFileTypes(c *gin.Context)

	// GetQuota Get /v1/admin/tenants/:tenantId/quota
	// Get storage quota
	GetQuota(c *gin.Context)

	// GetSettings Get /v1/admin/settings
	// Get system settings
	GetSettings(c *gin.Context)

	// GetTenant Get /v1/admin/tenants/:tenantId
	// Get tenant configuration
	GetTenant(c *gin.Context)

	// UpdateAllowedFileTypes Put /v1/admin/allowed-file-types
	// Update allowed file types
	UpdateAllowedFileTypes(c *gin.Context)

	// UpdateQuota Put /v1/admin/tenants/:tenantId/quota
	// Update storage quota
	UpdateQuota(c *gin.Context)

	// UpdateSettings Put /v1/admin/settings
	// Update system settings
	UpdateSettings(c *gin.Context)

	// UpdateTenant Put /v1/admin/tenants/:tenantId
	// Update tenant configuration
	UpdateTenant(c *gin.Context)
}
