/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type WorkflowsAPI interface {

	// ApproveStep Post /v1/workflows/:workflowId/steps/:stepId/approve
	// Approve workflow step
	ApproveStep(c *gin.Context)

	// CancelWorkflow Post /v1/workflows/:workflowId/cancel
	// Cancel workflow
	CancelWorkflow(c *gin.Context)

	// CreateWorkflow Post /v1/workflows
	// Assign approval workflow to a document
	CreateWorkflow(c *gin.Context)

	// CreateWorkflowTemplate Post /v1/workflow-templates
	// Create workflow template
	CreateWorkflowTemplate(c *gin.Context)

	// DeleteWorkflowTemplate Delete /v1/workflow-templates/:templateId
	// Delete workflow template
	DeleteWorkflowTemplate(c *gin.Context)

	// GetWorkflow Get /v1/workflows/:workflowId
	// Get workflow instance
	GetWorkflow(c *gin.Context)

	// GetWorkflowHistory Get /v1/workflows/:workflowId/history
	// Get workflow history
	GetWorkflowHistory(c *gin.Context)

	// GetWorkflowTemplate Get /v1/workflow-templates/:templateId
	// Get workflow template
	GetWorkflowTemplate(c *gin.Context)

	// ListWorkflowTemplates Get /v1/workflow-templates
	// List workflow templates
	ListWorkflowTemplates(c *gin.Context)

	// ListWorkflows Get /v1/workflows
	// List workflow instances
	ListWorkflows(c *gin.Context)

	// RejectStep Post /v1/workflows/:workflowId/steps/:stepId/reject
	// Reject workflow step
	RejectStep(c *gin.Context)

	// SubmitWorkflow Post /v1/workflows/:workflowId/submit
	// Submit document for approval
	SubmitWorkflow(c *gin.Context)

	// UpdateWorkflowTemplate Put /v1/workflow-templates/:templateId
	// Update workflow template
	UpdateWorkflowTemplate(c *gin.Context)
}
