/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type NotificationsAPI interface {

	// GetUnreadCount Get /v1/notifications/unread-count
	// Get unread notification count
	GetUnreadCount(c *gin.Context)

	// ListNotifications Get /v1/notifications
	// List notifications
	ListNotifications(c *gin.Context)

	// MarkAllNotificationsRead Post /v1/notifications/read-all
	// Mark all notifications as read
	MarkAllNotificationsRead(c *gin.Context)

	// MarkNotificationRead Post /v1/notifications/:notificationId/read
	// Mark notification as read
	MarkNotificationRead(c *gin.Context)
}
