/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type FilesAPI interface {

	// BulkDownload Post /v1/files/bulk-download
	// Bulk download files as ZIP
	BulkDownload(c *gin.Context)

	// BulkUploadFiles Post /v1/files/bulk
	// Bulk upload files
	BulkUploadFiles(c *gin.Context)

	// CopyFile Post /v1/files/:fileId/copy
	// Copy file
	CopyFile(c *gin.Context)

	// DeleteFile Delete /v1/files/:fileId
	// Delete file (moves to trash)
	DeleteFile(c *gin.Context)

	// DownloadFile Get /v1/files/:fileId/download
	// Download file
	DownloadFile(c *gin.Context)

	// GetAllFiles Get /v1/files
	// Get all files
	GetAllFiles(c *gin.Context)

	// GetFile Get /v1/files/:fileId
	// Get file metadata
	GetFile(c *gin.Context)

	// ListFileVersions Get /v1/files/:fileId/versions
	// List file versions
	ListFileVersions(c *gin.Context)

	// MoveFile Post /v1/files/:fileId/move
	// Move file
	MoveFile(c *gin.Context)

	// PreviewFile Get /v1/files/:fileId/preview
	// Get file preview
	PreviewFile(c *gin.Context)

	// RenameFile Patch /v1/files/:fileId
	// Rename file
	RenameFile(c *gin.Context)

	// RestoreFile Post /v1/files/:fileId/restore
	// Restore file from trash
	RestoreFile(c *gin.Context)

	// RestoreFileVersion Post /v1/files/:fileId/versions/:versionId/restore
	// Restore a specific file version
	RestoreFileVersion(c *gin.Context)

	// SetFileTags Put /v1/files/:fileId/tags
	// Set tags on file
	SetFileTags(c *gin.Context)

	// UploadFile Post /v1/files
	// Upload single file
	UploadFile(c *gin.Context)

	// UploadFileVersion Post /v1/files/:fileId/versions
	// Upload new file version
	UploadFileVersion(c *gin.Context)
}
