/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type AuthAPI interface {

	// ChangePassword Put /v1/auth/me/password
	// Change own password
	ChangePassword(c *gin.Context)

	// GetMe Get /v1/auth/me
	// Get current user profile
	GetMe(c *gin.Context)

	// Login Post /v1/auth/login
	// Login
	Login(c *gin.Context)

	// Logout Post /v1/auth/logout
	// Logout
	Logout(c *gin.Context)

	// RefreshToken Post /v1/auth/refresh
	// Refresh access token
	RefreshToken(c *gin.Context)

	// RegisterUser Post /v1/auth/register
	// Register user (admin only)
	RegisterUser(c *gin.Context)
}
