/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type FoldersAPI interface {

	// CopyFolder Post /v1/folders/:folderId/copy
	// Copy folder
	CopyFolder(c *gin.Context)

	// CreateFolder Post /v1/folders
	// Create folder
	CreateFolder(c *gin.Context)

	// DeleteFolder Delete /v1/folders/:folderId
	// Delete folder (moves to trash)
	DeleteFolder(c *gin.Context)

	// GetFilesByFolder Get /v1/folders/:folderId/files
	// Get all files in folder
	GetFilesByFolder(c *gin.Context)

	// GetFolder Get /v1/folders/:folderId
	// Get folder metadata
	GetFolder(c *gin.Context)

	// MoveFolder Post /v1/folders/:folderId/move
	// Move folder
	MoveFolder(c *gin.Context)

	// RenameFolder Patch /v1/folders/:folderId
	// Rename folder
	RenameFolder(c *gin.Context)

	// RestoreFolder Post /v1/folders/:folderId/restore
	// Restore folder from trash
	RestoreFolder(c *gin.Context)
}
