/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type ExplorerAPI interface {

	// GetBreadcrumb Get /v1/explorer/breadcrumb
	// Get breadcrumb path for a folder
	GetBreadcrumb(c *gin.Context)

	// ListDirectory Get /v1/explorer
	// List directory contents
	ListDirectory(c *gin.Context)

	// Search Get /v1/explorer/search
	// Search files and folders
	Search(c *gin.Context)
}
