/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"time"
)

type TenantResponse struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	// URL-safe identifier
	Slug string `json:"slug,omitempty"`

	LogoUrl *string `json:"logoUrl,omitempty"`

	PrimaryColor *string `json:"primaryColor,omitempty"`

	DefaultUserRole string `json:"defaultUserRole,omitempty"`

	SsoEnabled bool `json:"ssoEnabled,omitempty"`

	SsoProvider *string `json:"ssoProvider,omitempty"`

	MfaRequired bool `json:"mfaRequired,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
