/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"time"
)

type FileResponse struct {
	Id string `json:"id"`

	Name string `json:"name"`

	MimeType string `json:"mimeType"`

	Extension string `json:"extension,omitempty"`

	// File size in bytes
	Size int64 `json:"size"`

	FolderId *string `json:"folderId"`

	// Full logical path
	Path string `json:"path,omitempty"`

	OwnerId string `json:"ownerId"`

	Owner UserSummary `json:"owner,omitempty"`

	Status string `json:"status"`

	CurrentVersion int32 `json:"currentVersion,omitempty"`

	Tags []string `json:"tags,omitempty"`

	// MD5 or SHA-256 checksum
	Checksum string `json:"checksum,omitempty"`

	PreviewAvailable bool `json:"previewAvailable,omitempty"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`

	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}
