/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"time"
)

type WorkflowHistoryEvent struct {
	Id string `json:"id,omitempty"`

	EventType string `json:"eventType,omitempty"`

	Actor UserSummary `json:"actor,omitempty"`

	StepName *string `json:"stepName,omitempty"`

	Comment *string `json:"comment,omitempty"`

	OccurredAt time.Time `json:"occurredAt,omitempty"`
}
