/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type StorageStatsResponse struct {
	TotalQuotaBytes int64 `json:"totalQuotaBytes,omitempty"`

	UsedBytes int64 `json:"usedBytes,omitempty"`

	AvailableBytes int64 `json:"availableBytes,omitempty"`

	UsedPercent float64 `json:"usedPercent,omitempty"`

	TrashBytes int64 `json:"trashBytes,omitempty"`

	FileCount int64 `json:"fileCount,omitempty"`

	FolderCount int64 `json:"folderCount,omitempty"`

	ByUser []StorageStatsResponseByUserInner `json:"byUser,omitempty"`
}
