/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"time"
)

type WorkflowInstanceResponse struct {
	Id string `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Status string `json:"status,omitempty"`

	File FileResponse `json:"file,omitempty"`

	Template WorkflowTemplateResponse `json:"template,omitempty"`

	InitiatedBy UserSummary `json:"initiatedBy,omitempty"`

	Steps []WorkflowStepInstance `json:"steps,omitempty"`

	CurrentStep *int32 `json:"currentStep,omitempty"`

	DueDate *time.Time `json:"dueDate,omitempty"`

	CompletedAt *time.Time `json:"completedAt,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
