/*
 * Enterprise Document Management System API
 *
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`.
 *
 * API version: 1.0.0
 * Contact: api-support@dms.example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the AdminAPI part of the API
	AdminAPI AdminAPI
	// Routes for the AnalyticsAPI part of the API
	AnalyticsAPI AnalyticsAPI
	// Routes for the AuditAPI part of the API
	AuditAPI AuditAPI
	// Routes for the AuthAPI part of the API
	AuthAPI AuthAPI
	// Routes for the ExplorerAPI part of the API
	ExplorerAPI ExplorerAPI
	// Routes for the FilesAPI part of the API
	FilesAPI FilesAPI
	// Routes for the FoldersAPI part of the API
	FoldersAPI FoldersAPI
	// Routes for the NotificationsAPI part of the API
	NotificationsAPI NotificationsAPI
	// Routes for the SharingAPI part of the API
	SharingAPI SharingAPI
	// Routes for the TeamsAPI part of the API
	TeamsAPI TeamsAPI
	// Routes for the UsersAPI part of the API
	UsersAPI UsersAPI
	// Routes for the WorkflowsAPI part of the API
	WorkflowsAPI WorkflowsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		/*{
			"GetAllowedFileTypes",
			http.MethodGet,
			"/v1/admin/allowed-file-types",
			handleFunctions.AdminAPI.GetAllowedFileTypes,
		},
		{
			"GetQuota",
			http.MethodGet,
			"/v1/admin/tenants/:tenantId/quota",
			handleFunctions.AdminAPI.GetQuota,
		},
		{
			"GetSettings",
			http.MethodGet,
			"/v1/admin/settings",
			handleFunctions.AdminAPI.GetSettings,
		},
		{
			"GetTenant",
			http.MethodGet,
			"/v1/admin/tenants/:tenantId",
			handleFunctions.AdminAPI.GetTenant,
		},
		{
			"UpdateAllowedFileTypes",
			http.MethodPut,
			"/v1/admin/allowed-file-types",
			handleFunctions.AdminAPI.UpdateAllowedFileTypes,
		},
		{
			"UpdateQuota",
			http.MethodPut,
			"/v1/admin/tenants/:tenantId/quota",
			handleFunctions.AdminAPI.UpdateQuota,
		},
		{
			"UpdateSettings",
			http.MethodPut,
			"/v1/admin/settings",
			handleFunctions.AdminAPI.UpdateSettings,
		},
		{
			"UpdateTenant",
			http.MethodPut,
			"/v1/admin/tenants/:tenantId",
			handleFunctions.AdminAPI.UpdateTenant,
		},
		{
			"GetActivitySummary",
			http.MethodGet,
			"/v1/analytics/activity",
			handleFunctions.AnalyticsAPI.GetActivitySummary,
		},
		{
			"GetFileTypeStats",
			http.MethodGet,
			"/v1/analytics/file-types",
			handleFunctions.AnalyticsAPI.GetFileTypeStats,
		},
		{
			"GetStorageStats",
			http.MethodGet,
			"/v1/analytics/storage",
			handleFunctions.AnalyticsAPI.GetStorageStats,
		},
		{
			"GetWorkflowMetrics",
			http.MethodGet,
			"/v1/analytics/workflows",
			handleFunctions.AnalyticsAPI.GetWorkflowMetrics,
		},
		{
			"GetFileActivity",
			http.MethodGet,
			"/v1/audit/file-activity",
			handleFunctions.AuditAPI.GetFileActivity,
		},
		{
			"GetSecurityAudit",
			http.MethodGet,
			"/v1/audit/security",
			handleFunctions.AuditAPI.GetSecurityAudit,
		},
		{
			"GetUserActivity",
			http.MethodGet,
			"/v1/audit/user-activity",
			handleFunctions.AuditAPI.GetUserActivity,
		},
		{
			"ChangePassword",
			http.MethodPut,
			"/v1/auth/me/password",
			handleFunctions.AuthAPI.ChangePassword,
		},
		{
			"GetMe",
			http.MethodGet,
			"/v1/auth/me",
			handleFunctions.AuthAPI.GetMe,
		},
		*/{
			"Login",
			http.MethodPost,
			"/v1/auth/login",
			handleFunctions.AuthAPI.Login,
		},
		/*{
			"Logout",
			http.MethodPost,
			"/v1/auth/logout",
			handleFunctions.AuthAPI.Logout,
		},
		{
			"RefreshToken",
			http.MethodPost,
			"/v1/auth/refresh",
			handleFunctions.AuthAPI.RefreshToken,
		},
		{
			"RegisterUser",
			http.MethodPost,
			"/v1/auth/register",
			handleFunctions.AuthAPI.RegisterUser,
		},
		{
			"GetBreadcrumb",
			http.MethodGet,
			"/v1/explorer/breadcrumb",
			handleFunctions.ExplorerAPI.GetBreadcrumb,
		},
		{
			"ListDirectory",
			http.MethodGet,
			"/v1/explorer",
			handleFunctions.ExplorerAPI.ListDirectory,
		},
		{
			"Search",
			http.MethodGet,
			"/v1/explorer/search",
			handleFunctions.ExplorerAPI.Search,
		},
		{
			"BulkDownload",
			http.MethodPost,
			"/v1/files/bulk-download",
			handleFunctions.FilesAPI.BulkDownload,
		},
		{
			"BulkUploadFiles",
			http.MethodPost,
			"/v1/files/bulk",
			handleFunctions.FilesAPI.BulkUploadFiles,
		},
		{
			"CopyFile",
			http.MethodPost,
			"/v1/files/:fileId/copy",
			handleFunctions.FilesAPI.CopyFile,
		},
		{
			"DeleteFile",
			http.MethodDelete,
			"/v1/files/:fileId",
			handleFunctions.FilesAPI.DeleteFile,
		},*/
		{
			"DownloadFile",
			http.MethodGet,
			"/v1/files/:fileId/download",
			handleFunctions.FilesAPI.DownloadFile,
		},
		{
			"GetAllFiles",
			http.MethodGet,
			"/v1/files",
			handleFunctions.FilesAPI.GetAllFiles,
		},
		{
			"GetFile",
			http.MethodGet,
			"/v1/files/:fileId",
			handleFunctions.FilesAPI.GetFile,
		},
		/*{
			"ListFileVersions",
			http.MethodGet,
			"/v1/files/:fileId/versions",
			handleFunctions.FilesAPI.ListFileVersions,
		},
		{
			"MoveFile",
			http.MethodPost,
			"/v1/files/:fileId/move",
			handleFunctions.FilesAPI.MoveFile,
		},
		{
			"PreviewFile",
			http.MethodGet,
			"/v1/files/:fileId/preview",
			handleFunctions.FilesAPI.PreviewFile,
		},
		{
			"RenameFile",
			http.MethodPatch,
			"/v1/files/:fileId",
			handleFunctions.FilesAPI.RenameFile,
		},
		{
			"RestoreFile",
			http.MethodPost,
			"/v1/files/:fileId/restore",
			handleFunctions.FilesAPI.RestoreFile,
		},
		{
			"RestoreFileVersion",
			http.MethodPost,
			"/v1/files/:fileId/versions/:versionId/restore",
			handleFunctions.FilesAPI.RestoreFileVersion,
		},
		{
			"SetFileTags",
			http.MethodPut,
			"/v1/files/:fileId/tags",
			handleFunctions.FilesAPI.SetFileTags,
		},
		*/{
			"UploadFile",
			http.MethodPost,
			"/v1/files",
			handleFunctions.FilesAPI.UploadFile,
		},
		/*{
			"UploadFileVersion",
			http.MethodPost,
			"/v1/files/:fileId/versions",
			handleFunctions.FilesAPI.UploadFileVersion,
		},
		{
			"CopyFolder",
			http.MethodPost,
			"/v1/folders/:folderId/copy",
			handleFunctions.FoldersAPI.CopyFolder,
		},
		{
			"CreateFolder",
			http.MethodPost,
			"/v1/folders",
			handleFunctions.FoldersAPI.CreateFolder,
		},
		{
			"DeleteFolder",
			http.MethodDelete,
			"/v1/folders/:folderId",
			handleFunctions.FoldersAPI.DeleteFolder,
		},
		{
			"GetFilesByFolder",
			http.MethodGet,
			"/v1/folders/:folderId/files",
			handleFunctions.FoldersAPI.GetFilesByFolder,
		},
		{
			"GetFolder",
			http.MethodGet,
			"/v1/folders/:folderId",
			handleFunctions.FoldersAPI.GetFolder,
		},
		{
			"MoveFolder",
			http.MethodPost,
			"/v1/folders/:folderId/move",
			handleFunctions.FoldersAPI.MoveFolder,
		},
		{
			"RenameFolder",
			http.MethodPatch,
			"/v1/folders/:folderId",
			handleFunctions.FoldersAPI.RenameFolder,
		},
		{
			"RestoreFolder",
			http.MethodPost,
			"/v1/folders/:folderId/restore",
			handleFunctions.FoldersAPI.RestoreFolder,
		},
		{
			"GetUnreadCount",
			http.MethodGet,
			"/v1/notifications/unread-count",
			handleFunctions.NotificationsAPI.GetUnreadCount,
		},
		{
			"ListNotifications",
			http.MethodGet,
			"/v1/notifications",
			handleFunctions.NotificationsAPI.ListNotifications,
		},
		{
			"MarkAllNotificationsRead",
			http.MethodPost,
			"/v1/notifications/read-all",
			handleFunctions.NotificationsAPI.MarkAllNotificationsRead,
		},
		{
			"MarkNotificationRead",
			http.MethodPost,
			"/v1/notifications/:notificationId/read",
			handleFunctions.NotificationsAPI.MarkNotificationRead,
		},
		{
			"CreateShare",
			http.MethodPost,
			"/v1/shares",
			handleFunctions.SharingAPI.CreateShare,
		},
		{
			"GeneratePublicLink",
			http.MethodPost,
			"/v1/shares/public-links",
			handleFunctions.SharingAPI.GeneratePublicLink,
		},
		{
			"GetAcl",
			http.MethodGet,
			"/v1/shares/:resourceType/:resourceId",
			handleFunctions.SharingAPI.GetAcl,
		},
		{
			"RevokeAccess",
			http.MethodDelete,
			"/v1/shares/:resourceType/:resourceId/entries/:principalId",
			handleFunctions.SharingAPI.RevokeAccess,
		},
		{
			"RevokeAllShares",
			http.MethodDelete,
			"/v1/shares/:resourceType/:resourceId",
			handleFunctions.SharingAPI.RevokeAllShares,
		},
		{
			"RevokePublicLink",
			http.MethodDelete,
			"/v1/shares/public-links/:token",
			handleFunctions.SharingAPI.RevokePublicLink,
		},
		{
			"UpdatePermission",
			http.MethodPut,
			"/v1/shares/:resourceType/:resourceId/entries/:principalId",
			handleFunctions.SharingAPI.UpdatePermission,
		},
		{
			"AddTeamMembers",
			http.MethodPost,
			"/v1/teams/:teamId/members",
			handleFunctions.TeamsAPI.AddTeamMembers,
		},
		{
			"CreateTeam",
			http.MethodPost,
			"/v1/teams",
			handleFunctions.TeamsAPI.CreateTeam,
		},
		{
			"DeleteTeam",
			http.MethodDelete,
			"/v1/teams/:teamId",
			handleFunctions.TeamsAPI.DeleteTeam,
		},
		{
			"GetTeam",
			http.MethodGet,
			"/v1/teams/:teamId",
			handleFunctions.TeamsAPI.GetTeam,
		},
		{
			"ListTeamMembers",
			http.MethodGet,
			"/v1/teams/:teamId/members",
			handleFunctions.TeamsAPI.ListTeamMembers,
		},
		{
			"ListTeams",
			http.MethodGet,
			"/v1/teams",
			handleFunctions.TeamsAPI.ListTeams,
		},
		{
			"RemoveTeamMembers",
			http.MethodDelete,
			"/v1/teams/:teamId/members",
			handleFunctions.TeamsAPI.RemoveTeamMembers,
		},
		{
			"UpdateTeam",
			http.MethodPut,
			"/v1/teams/:teamId",
			handleFunctions.TeamsAPI.UpdateTeam,
		},
		{
			"AssignRoles",
			http.MethodPut,
			"/v1/users/:userId/roles",
			handleFunctions.UsersAPI.AssignRoles,
		},
		{
			"DeleteUser",
			http.MethodDelete,
			"/v1/users/:userId",
			handleFunctions.UsersAPI.DeleteUser,
		},
		{
			"GetUserById",
			http.MethodGet,
			"/v1/users/:userId",
			handleFunctions.UsersAPI.GetUserById,
		},
		{
			"ListUsers",
			http.MethodGet,
			"/v1/users",
			handleFunctions.UsersAPI.ListUsers,
		},
		{
			"UpdateProfile",
			http.MethodPatch,
			"/v1/users/:userId/profile",
			handleFunctions.UsersAPI.UpdateProfile,
		},
		{
			"UpdateUser",
			http.MethodPut,
			"/v1/users/:userId",
			handleFunctions.UsersAPI.UpdateUser,
		},
		{
			"ApproveStep",
			http.MethodPost,
			"/v1/workflows/:workflowId/steps/:stepId/approve",
			handleFunctions.WorkflowsAPI.ApproveStep,
		},
		{
			"CancelWorkflow",
			http.MethodPost,
			"/v1/workflows/:workflowId/cancel",
			handleFunctions.WorkflowsAPI.CancelWorkflow,
		},
		{
			"CreateWorkflow",
			http.MethodPost,
			"/v1/workflows",
			handleFunctions.WorkflowsAPI.CreateWorkflow,
		},
		{
			"CreateWorkflowTemplate",
			http.MethodPost,
			"/v1/workflow-templates",
			handleFunctions.WorkflowsAPI.CreateWorkflowTemplate,
		},
		{
			"DeleteWorkflowTemplate",
			http.MethodDelete,
			"/v1/workflow-templates/:templateId",
			handleFunctions.WorkflowsAPI.DeleteWorkflowTemplate,
		},
		{
			"GetWorkflow",
			http.MethodGet,
			"/v1/workflows/:workflowId",
			handleFunctions.WorkflowsAPI.GetWorkflow,
		},
		{
			"GetWorkflowHistory",
			http.MethodGet,
			"/v1/workflows/:workflowId/history",
			handleFunctions.WorkflowsAPI.GetWorkflowHistory,
		},
		{
			"GetWorkflowTemplate",
			http.MethodGet,
			"/v1/workflow-templates/:templateId",
			handleFunctions.WorkflowsAPI.GetWorkflowTemplate,
		},
		{
			"ListWorkflowTemplates",
			http.MethodGet,
			"/v1/workflow-templates",
			handleFunctions.WorkflowsAPI.ListWorkflowTemplates,
		},
		{
			"ListWorkflows",
			http.MethodGet,
			"/v1/workflows",
			handleFunctions.WorkflowsAPI.ListWorkflows,
		},
		{
			"RejectStep",
			http.MethodPost,
			"/v1/workflows/:workflowId/steps/:stepId/reject",
			handleFunctions.WorkflowsAPI.RejectStep,
		},
		{
			"SubmitWorkflow",
			http.MethodPost,
			"/v1/workflows/:workflowId/submit",
			handleFunctions.WorkflowsAPI.SubmitWorkflow,
		},
		{
			"UpdateWorkflowTemplate",
			http.MethodPut,
			"/v1/workflow-templates/:templateId",
			handleFunctions.WorkflowsAPI.UpdateWorkflowTemplate,
		},*/
	}
}
func getDefaultHandlerFunctions(apiClass interface{}, handlerFunc gin.HandlerFunc) gin.HandlerFunc {
	if apiClass == nil {
		return DefaultHandleFunc
	}
	return handlerFunc
}
